### PR TITLE
Ng

### PR DESCRIPTION
**Pull request by ChristopherHX**

### CODE REVIEW

**Comment by nazthelizard122** [comment]
is this what you are talking about?

**Comment by ChristopherHX** [comment]
No, this is outdated. Failed test
Find it here
https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/ng.appimage

**Comment by nazthelizard122** [comment]
Ok does it matter which x86 I get?

**Comment by ChristopherHX** [comment]
Yes, or it will need an update https://github.com/minecraft-linux/mcpelauncher-manifest/issues/420#issuecomment-721768062

**Comment by nazthelizard122** [comment]
11:20:02 Trace [HybrisUtils] Loaded OS library libz.so.1
11:20:02 Trace [HybrisUtils] Loaded OS library libm.so.6
11:20:02 Trace [HybrisUtils] Loaded OS library /tmp/.mount_MinecreZ4PYz/usr/share/mcpelauncher/lib/native/x86_64/libfmod.so.12.0
11:20:02 Info  [Launcher] Loading gamepad mappings
11:20:02 Trace [Launcher] Loading gamepad mappings: /tmp/.mount_MinecreZ4PYz/usr/share/mcpelauncher/gamecontrollerdb.txt
11:20:02 Info  [Launcher] Creating window
11:20:02 Info  [Minecraft] android_main starting. internalDataPath is '../data/', externalDataPath is '../data/'
11:20:02 Info  [Minecraft] NO LOG FILE! - AppPlatform_android::setStorageDirectory - using External dir - CurrentFileStoragePath is now '/home/naz/.local/share/mcpelauncher/'
11:20:02 Warn  [Launcher] EGL stub eglMakeCurrent called
11:20:02 Warn  [Launcher] EGL stub eglMakeCurrent called
11:20:02 Warn  [Launcher] EGL stub eglMakeCurrent called
11:20:02 Warn  [Minecraft] NO LOG FILE! - [Device Lost] The graphics context was gained
11:20:02 Warn  [Minecraft] MinecraftGame::init && MinecraftGame::setSize!
11:20:03 Debug [HttpCallStaticGlue] Successfully registerered HttpCall methods
11:20:03 Debug [XboxLiveAppConfig] Successfully registerered XboxLiveAppConfig methods
11:20:03 Debug [XSAPI.Android] Successfully registerered HttpCall tcuiMethods
11:20:03 Debug [XSAPI.Android] Successfully registerered telemetryMethods
11:20:16 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 46372
11:20:16 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 43588
11:20:16 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 36094
11:20:16 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 40253
11:20:47 Info  [Minecraft] NO LOG FILE! - opening /home/naz/.local/share/mcpelauncher/minecraftpe/blob_cache
12:47:16 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 46372
12:47:16 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 43588
12:47:19 Info  [Minecraft] NO LOG FILE! - opening /home/naz/.local/share/mcpelauncher/minecraftpe/blob_cache
12:47:19 Info  [Minecraft] NO LOG FILE! - IPv4 supported, port: 36094
12:47:19 Info  [Minecraft] NO LOG FILE! - IPv6 supported, port: 40253
terminating with uncaught exception of type std::__ndk1::system_error: mutex lock failed: Unknown error 22
abort message: terminating with uncaught exception of type std::__ndk1::system_error: mutex lock failed: Unknown error 22
Signal 6 received
Backtrace elements: 5
#0 /tmp/.mount_MinecreZ4PYz/usr/bin/./mcpelauncher-client(_ZN12CrashHandler12handleSignalEiPv+0xc3) [0xb9c113]
#1 /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0) [0x7f36810253c0]
#2 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f368023b18b]
#3 /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f368021a859]
#4 HYBRIS (null)+0x7f36783a508c in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xa508c [0x0x7f36783a508c]
Dumping stack...
#15 HYBRIS (null)+0x7f36783c3200 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc3200 [0x0x7f36783c3200]
#37 HYBRIS (null)+0x7f36783c31fe in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc31fe [0x0x7f36783c31fe]
#47 HYBRIS (null)+0x7f36783c31fd in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc31fd [0x0x7f36783c31fd]
#57 HYBRIS (null)+0x7f36783c322b in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc322b [0x0x7f36783c322b]
#261 HYBRIS (null)+0x7f36783a508c in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xa508c [0x0x7f36783a508c]
#262 HYBRIS (null)+0x7f36783bdcc0 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xbdcc0 [0x0x7f36783bdcc0]
#271 HYBRIS typeinfo for std::__ndk1::system_error+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xecd80 [0x0x7f36783ecd80]
#272 HYBRIS typeinfo for __cxxabiv1::__shim_type_info+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xeecd8 [0x0x7f36783eecd8]
#273 HYBRIS (null)+0x7f36783c3288 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc3288 [0x0x7f36783c3288]
#276 HYBRIS typeinfo for std::exception+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xef888 [0x0x7f36783ef888]
#281 HYBRIS typeinfo for std::exception+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xef888 [0x0x7f36783ef888]
#283 HYBRIS (null)+0x7f36783bce0a in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xbce0a [0x0x7f36783bce0a]
#285 HYBRIS typeinfo for std::__ndk1::system_error+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xecd80 [0x0x7f36783ecd80]
#287 HYBRIS typeinfo for std::exception+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xef888 [0x0x7f36783ef888]
#294 HYBRIS (null)+0x7f36783c3288 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc3288 [0x0x7f36783c3288]
#298 HYBRIS typeinfo for std::__ndk1::system_error+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xecd80 [0x0x7f36783ecd80]
#299 HYBRIS (null)+0x7f36783a524e in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xa524e [0x0x7f36783a524e]
#320 HYBRIS typeinfo for std::__ndk1::system_error+(nil) in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xecd80 [0x0x7f36783ecd80]
#321 HYBRIS (null)+0x7f36783c023d in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc023d [0x0x7f36783c023d]
#341 HYBRIS (null)+0x64 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xba614 [0x0x7f36783ba614]
#345 HYBRIS (null)+0x7f36783c01e2 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc01e2 [0x0x7f36783c01e2]
#375 HYBRIS (null)+0x7f3662323c50 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x41a3c50 [0x0x7f3662323c50]
#428 HYBRIS (null)+0x7f36783bac30 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xbac30 [0x0x7f36783bac30]
#431 HYBRIS (null)+0x23 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xbab83 [0x0x7f36783bab83]
#435 HYBRIS (null)+0x7f36783bafa3 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xbafa3 [0x0x7f36783bafa3]
#437 HYBRIS (null)+0x7f36783ba6a6 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xba6a6 [0x0x7f36783ba6a6]
#439 HYBRIS (null)+0x7f36783ba61c in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xba61c [0x0x7f36783ba61c]
#443 HYBRIS (null)+0x7f36783c28c9 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xc28c9 [0x0x7f36783c28c9]
#445 HYBRIS std::__ndk1::__throw_system_error(int, char const*)+0x74 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0xa4264 [0x0x7f36783a4264]
#449 HYBRIS (null)+0x7f36783995da in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libc++_shared.so+0x0x995da [0x0x7f36783995da]
#451 HYBRIS BackgroundTask::_tryTransitionTo(BackgroundTask::TaskStatus, bool, bool)+0x28 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x4183d38 [0x0x7f3662303d38]
#461 HYBRIS (null)+0x7f3662304abc in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x4184abc [0x0x7f3662304abc]
#469 HYBRIS BackgroundTask::_tryTransitionTo(BackgroundTask::TaskStatus, bool, bool)+0x2e6 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x4183ff6 [0x0x7f3662303ff6]
#479 HYBRIS BackgroundTask::run(ITaskExecutionContext const*)+0x191 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x4184471 [0x0x7f3662304471]
#499 HYBRIS BackgroundWorker::_runOneTask()+0xbd in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x41a3a5d [0x0x7f3662323a5d]
#511 HYBRIS BackgroundWorker::_processNextTask()+0x20 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x41a3700 [0x0x7f3662323700]
#515 HYBRIS (null)+0x7f3662323d12 in /home/naz/.local/share/mcpelauncher/versions/1.16.20.03/lib/x86_64/libminecraftpe.so+0x0x41a3d12 [0x0x7f3662323d12]

Process exited with unexpected exit code: 6

**Comment by ChristopherHX** [comment]
That error is random and one reason why it is called unstable.

This pr is redundant.

**Comment by nazthelizard122** [comment]
Ok

**Pull request closed without merging**
